spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      parameter-store:
        enabled: false

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

  #  임시로 주석처리. 확인되면 삭제
#  autoconfigure:
#    exclude:
#      - org.redisson.spring.starter.RedissonAutoConfigurationV2

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token-expiration: ${access.token.expiration:3600000}
  refresh-token-expiration: ${refresh.token.expiration:1209600000}

toss:
  secret:
    key: ${TOSS_SECRET_KEY}

springdoc:
  api-docs.enabled: false
  swagger-ui:
    enabled: false